=== Ce1ikE/Web_Engineering/Labo 10/Reeks 27/Oefening_27_4.dtd
<!ELEMENT adressen (adres+)>
    <!ELEMENT adres (naam,voornaam+,straat-nummer?,plaats,(telefoon-nummer|gsm-nummer),email?)>
        <!ELEMENT naam (#PCDATA)>
        <!ELEMENT voornaam (#PCDATA)>
        <!ELEMENT straat-nummer (#PCDATA)>
        <!ELEMENT plaats (#PCDATA)>
        <!ELEMENT telefoon-nummer (#PCDATA)>
        <!ELEMENT gsm-nummer (#PCDATA)>
        <!ELEMENT email (#PCDATA)>

=== Ce1ikE/Web_Engineering/Labo 10/Reeks 27/Oefening_27_4.xml
<?xml version="1.0" encoding="UTF-8"?>
<!DOCTYPE adressen SYSTEM "./Oefening_27_4.dtd">
<adressen>
    <adres>                                     <!-- + -->
        <naam></naam>                           <!-- 1 -->
        <voornaam></voornaam>                   <!-- + -->
        <voornaam></voornaam>                   <!-- + -->
        <voornaam></voornaam>                   <!-- + -->
        <straat-nummer></straat-nummer>         <!-- NOT REQUIRED -->
        <plaats></plaats>                       <!-- 1 -->
        <telefoon-nummer></telefoon-nummer>     <!-- of gsm -->
        <!-- <gsm-nummer></gsm-nummer> -->      <!-- of telefoon -->
        <email></email>                         <!-- NOT REQUIRED -->
    </adres> 
    <adres>                                     
        <naam></naam>                           
        <voornaam></voornaam>                                   
        <straat-nummer></straat-nummer>         
        <plaats></plaats>                      
        <telefoon-nummer></telefoon-nummer>     
        <!-- <gsm-nummer></gsm-nummer> -->
        <email></email>                         
    </adres>     
    <adres>                                     
        <naam></naam>                                                              
        <voornaam></voornaam>                         
        <plaats></plaats>                      
        <telefoon-nummer></telefoon-nummer>                                   
    </adres>
    <adres>                                     
        <naam></naam>                                                             
        <voornaam></voornaam>                         
        <plaats></plaats>                      
        <gsm-nummer></gsm-nummer>                                 
    </adres>                     
</adressen>
