=== Ce1ikE/Web_Engineering/Labo 11/Reeks 28/Oefening_28_4.xsd
<?xml version="1.0" encoding="UTF-8"?>
<xs:schema xmlns:xs="http://www.w3.org/2001/XMLSchema">
    <xs:element name="gedicht" type="gedicht-type"/>

    <xs:complexType name="gedicht-type">
        <xs:sequence>
            <xs:element name="titel" type="xs:string"  minOccurs="1" maxOccurs="1"/>
            <xs:element name="strofe" type="strofe-type"/>
            <xs:element name="auteur" type="xs:string"  minOccurs="1" maxOccurs="1"/>
            <xs:element name="data" type="xs:string"  minOccurs="1" maxOccurs="1"/>
        </xs:sequence>
    </xs:complexType>

    <xs:complexType name="strofe-type">
        <xs:sequence>
            <xs:element name="vers" type="xs:string" minOccurs="1" maxOccurs="unbounded"/>
        </xs:sequence>
    </xs:complexType>
</xs:schema>

=== Ce1ikE/Web_Engineering/Labo 11/Reeks 28/Oefening_28_4.xml
<?xml version="1.0" encoding="UTF-8" standalone="yes" ?>
<gedicht xmlns:xsi="http://www.w3.org/2001/XMLSchema-instance" xsi:noNamespaceSchemaLocation="Oefening_28_4.xsd">
    <titel>De waterlelie</titel>
    <strofe>
        <vers>Ik heb de witte water-lelie lief,</vers>
        <vers>daar die zo blank is en zo stil haar kroon</vers>
        <vers>uitplooit in 't licht.</vers>
        <vers>Rijzend uit donker-koele vijvergrond,</vers>
        <vers>heeft zij het licht gevonden en ontsloot</vers>
        <vers>toen blij het gouden hart.</vers>
        <vers>Nu rust zij peinzend op het watervlak</vers>
        <vers>en wenst niet meer...</vers>
    </strofe>
    <auteur>Frederik van Eeden</auteur>
    <data>1860 - 1932</data>
</gedicht>
