=== Ce1ikE/Web_Engineering/Labo 11/Startbestanden/Starbestanden_labo11/Oefening_28_1.xsd
<?xml version="1.0" encoding="UTF-8"?>
<xs:schema xmlns:xs="http://www.w3.org/2001/XMLSchema" elementFormDefault="qualified">
    <xs:element name="patient" type="patientType" />

    <xs:complexType name="patientType">
      <xs:sequence>
        <xs:element name="naam" type="xs:string"  />
        <xs:element name="geslacht" type="geslachtType" />
        <xs:element name="nr" type="xs:integer"  />
        <xs:element name="medische-gegevens" type="mgegevensType" />
      </xs:sequence>
    </xs:complexType>

    <xs:complexType name="mgegevensType">
      <xs:sequence>
        <xs:element name="gegeven" type="xs:string" maxOccurs="unbounded" />
     </xs:sequence>
    </xs:complexType>

    <xs:simpleType name="geslachtType">
      <xs:restriction base="xs:string">
        <xs:enumeration value="m" />
        <xs:enumeration value="f" />
      </xs:restriction>
    </xs:simpleType>
</xs:schema>

=== Ce1ikE/Web_Engineering/Labo 11/Reeks 28/Oefening_28_1_patient1.xml
<?xml version="1.0" encoding="UTF-8" ?>
<patient xmlns:xsi="http://www.w3.org/2001/XMLSchema-instance" xsi:noNamespaceSchemaLocation="Oefening_28_1.xsd">
    <naam>Jan Versmissen</naam>
    <geslacht>m</geslacht>
    <nr>123456</nr>
    <medische-gegevens>
        <gegeven>geboren 1921</gegeven>
        <gegeven>zeer slecht ziend</gegeven>
        <gegeven>verzorgingstehuis</gegeven>
        <gegeven>verder geen medische gegevens</gegeven>
    </medische-gegevens>
</patient>
